# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_tracker_db
spring.datasource.username=postgres
spring.datasource.password=Olzhas1906!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=false

# Server
server.port=8080

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Spring Security
jwt.secret=b7f3c2a9d8e14f6bb2c4a5e9f0d3c7a8e6b1d9f4c2a7e8b3f1d6c9a2e5f7b8c1
jwt.expiration=8640000